// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const firefox = require('selenium-webdriver/firefox')
const assert = require('assert')

describe('toka resti', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    const options = new firefox.Options().headless()   // ⬅ headless Firefox
    driver = await new Builder()
      .forBrowser('firefox')
      .setFirefoxOptions(options)
      .build()
    vars = {}
  })

  afterEach(async function() {
    if (driver) {          // ⬅ älä yritä quitata, jos driveria ei ole
      await driver.quit()
    }
  })
  async function waitForWindow(timeout = 2000) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('toka resti', async function() {
    await driver.get("https://jennioksman.netlify.app/")
    await driver.manage().window().setRect({ width: 1382, height: 744 })
    await driver.findElement(By.linkText("Minä")).click()
    await driver.findElement(By.linkText("Projektini")).click()
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["root"])
    await driver.switchTo().window(vars["root"])
     vars["windowHandles"] = await driver.getAllWindowHandles()

    const boredDemoLink = await driver.findElement(
    By.xpath("//a[contains(@href, 'getdrink.netlify.app')]")
  )
  await boredDemoLink.click()
    const newWindow = await waitForWindow(2000)
    await driver.switchTo().window(newWindow)
    await driver.switchTo().window(vars["root"])
    await driver.switchTo().window(vars["root"])
    await driver.findElement(By.linkText("Osaamiseni")).click()
  })
})


